#Basic Spring Boot Config for Oracle
# Settings for the oracle connection
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: authdb
    password: pass123$
    driver-class-name: oracle.jdbc.OracleDriver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
